name: Auto-approve Dependabot PRs
on:
  - pull_request
  - schedule:
    - cron: "42 * * * *"

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          approve: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
